name: clock_challenge
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  #计时器页面用到的TimePicker控件
#  flutter_cupertino_date_picker: ^1.0.26+2
  #目前官方版本存在问题
  flutter_cupertino_date_picker:
    git: https://github.com/daveleenew/flutter-cupertino-date-picker.git

  #网络请求
  dio: ^3.0.10

  #传感器
  sensors: '>=0.4.2+4 <2.0.0'

  #震动反馈
  flutter_vibrate: ^1.0.0

  #数据持久化
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  # assets-generator-begin
    - assets/weather_icons/100.png
    - assets/weather_icons/101.png
    - assets/weather_icons/102.png
    - assets/weather_icons/103.png
    - assets/weather_icons/104.png
    - assets/weather_icons/150.png
    - assets/weather_icons/153.png
    - assets/weather_icons/154.png
    - assets/weather_icons/300.png
    - assets/weather_icons/301.png
    - assets/weather_icons/302.png
    - assets/weather_icons/303.png
    - assets/weather_icons/304.png
    - assets/weather_icons/305.png
    - assets/weather_icons/306.png
    - assets/weather_icons/307.png
    - assets/weather_icons/308.png
    - assets/weather_icons/309.png
    - assets/weather_icons/310.png
    - assets/weather_icons/311.png
    - assets/weather_icons/312.png
    - assets/weather_icons/313.png
    - assets/weather_icons/314.png
    - assets/weather_icons/315.png
    - assets/weather_icons/316.png
    - assets/weather_icons/317.png
    - assets/weather_icons/318.png
    - assets/weather_icons/350.png
    - assets/weather_icons/351.png
    - assets/weather_icons/399.png
    - assets/weather_icons/400.png
    - assets/weather_icons/401.png
    - assets/weather_icons/402.png
    - assets/weather_icons/403.png
    - assets/weather_icons/404.png
    - assets/weather_icons/405.png
    - assets/weather_icons/406.png
    - assets/weather_icons/407.png
    - assets/weather_icons/408.png
    - assets/weather_icons/409.png
    - assets/weather_icons/410.png
    - assets/weather_icons/456.png
    - assets/weather_icons/457.png
    - assets/weather_icons/499.png
    - assets/weather_icons/500.png
    - assets/weather_icons/501.png
    - assets/weather_icons/502.png
    - assets/weather_icons/503.png
    - assets/weather_icons/504.png
    - assets/weather_icons/507.png
    - assets/weather_icons/508.png
    - assets/weather_icons/509.png
    - assets/weather_icons/510.png
    - assets/weather_icons/511.png
    - assets/weather_icons/512.png
    - assets/weather_icons/513.png
    - assets/weather_icons/514.png
    - assets/weather_icons/515.png
    - assets/weather_icons/900.png
    - assets/weather_icons/901.png
    - assets/weather_icons/999.png
  # assets-generator-end

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
